apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: bypass-jwt-for-obstester
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: istio-shared-gateway
  configPatches:
  - applyTo: HTTP_ROUTE
    match:
      context: GATEWAY
      routeConfiguration:
        vhost:
          name: "httpbin.internal.io:443"  # Adjust the host and port as needed
    patch:
      operation: MERGE
      value:
        typed_per_filter_config:
          envoy.filters.http.jwt_authn:
            "@type": type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.PerRouteConfig
            disabled: true